### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by VPRzhou** [germain-hug/S2DHM#3]
Hi,I have a running question to consult you.When I do the command" python3 run.py --dataset cmu --mode sparse_to_dense",there is an error to arise.

Traceback (most recent call last):
  File "run.py", line 7, in <module>
    from image_retrieval import rank_images
  File "/home/zhoul/S2DHM/s2dhm/image_retrieval/rank_images.py", line 6, in <module>
    from datasets import base_dataset
ImportError: cannot import name 'base_dataset'
Could you tell me the reason.Thanks a lot.

**Comment by germain-hug** [comment]
Hi, 
Apologies for the delay, which version of Python are you using?
It seems like this is a dependency issue, are you running the code from the s2dhm/ folder?

**Comment by VPRzhou** [comment]
Hi,the problem was solved.But I want reproduce the result of the sparse-to-dense matching approach using hypercolumn descriptors.Could you show me the process of matching code?
Thank you a lot!

**Comment by VPRzhou** [comment]
sorry,another question I want to ask you.If I want to compare your method to some other methods,such as DELF、LF-Net and so on.How can I do the process of evalution of their performance on changing environments and draw a curve in the coordinate axis,what is the definition of X axis and Y axis?
